### ISSUE TITLE
How is probability calculated?

### ISSUE THREAD

**Issue by gbacoins** [bcsongor/tinyvanityeth#6]
Please share more details on "Probability".  Is the script calculating this based on how many addresses it already checked?

**Comment by bcsongor** [comment]
Hey @gbacoins 

Indeed the formula is as follows: 

$$P=1-\left(1−\frac{1}{difficulty}\right)^{generated}$$

The probability depends on the $difficulty$ of finding an address that conforms to the given rules (for simple cases this is the total number of possible unique matching addresses). This is then used in the above formula (derived from Bernoulli trials) which calculates the chance of finding a matching address at least once, given many attempts ($generated$), where each attempt has a relatively small but fixed chance of success.

Hope this answers your question, let me know if you have further thoughts!
